### ISSUE TITLE
Model3D importer

### ISSUE THREAD

**Issue by bztsrc** [goxel2/goxel2#15]
Hi,

As promised here's the importer (exporter unchanged). I was lucky because I remembered I have [already implemented](https://gitlab.com/bztsrc/mtsedit/-/blob/master/src/schemimp.c) a separate voxel-only loader, so I could reuse 99% of that code :-)

[m3d.c.gz](https://github.com/pegvin/goxel2/files/9244638/m3d.c.gz)

Few notes:
1. sorry, creating PRs still not working for me after recent github changes
2. this version does not use the M3D SDK, it is a standalone implementation, so just replace m3d.c and you're good to go
3. it can reliably read in all m3d files saved with the goxel exporter
4. it can also read in even some variants that the goxel exporter can't save

For example, the exporter always saves 16 bit coordinates and 16 bit indices, but the importer also works with 8 bit and 32 bit coordinates and smaller 8 bit indices as well, and works if colormap is used too. It also loads back the layer's name if stored in the file (but the exported does not save any strings nor colormap into the models for simplicity).

Now the support is complete, load/save works, but in order to take advantage of all the Model3D features, one would have to rewrite this code using the M3D SDK. I'm not entirely sure it worth it though. Maybe the variable coordinate and index size and the layer name are the only features it could really benefit from. Most of the additional features in the SDK are irrelevant for goxel anyway (converting voxels to triangle mesh, calculating smooth normals, bone weight cross-references, skeleton transformation matrices, etc. etc. etc.)

Anyway, if you are still interested in using the official M3D SDK, let me know.

Cheers,
bzt

ps: take a look at the linked schemimp.c, you might find it useful. Besides of m3d, it also implements importers for Minecraft schematic files (both original NBT and Sponge NBT), qubicle files, Tiled tmx files, WorldEdit .we files etc. Schematics usually use a numeric ID or a named voxel type, so you'll have to add a default palette for those (same as with old .vox format). Links to their corresponding file format specs are [here](https://gitlab.com/bztsrc/mtsedit/-/blob/master/docs/import.md).

**Comment by pegvin** [comment]
Ah man, you're just genius! Will look into it in few hours

**Comment by bztsrc** [comment]
Ah, sorry for the indentation issues. As I've said, this code is mostly reused from another project and I haven't noticed that copy'n'pasting messed up the indentation because my IDE isn't configured properly yet (I had to reinstall my computer not so long ago, lost IDE config during the process). Mea culpa!

Since there's a PR for this, I guess we can close this issue.

Cheers,
bzt

**Comment by pegvin** [comment]
hey don't worry everything was fine, i just converted the spaces to tabs, nothing more or less, thanks again for the Help!
