### ISSUE TITLE
Import Schematics

### ISSUE THREAD

**Issue by bztsrc** [goxel2/goxel2#17]
Hi,

Here's a new format file,

[schem.c.gz](https://github.com/goxel2/goxel2/files/9276267/schem.c.gz)

which can import Minetest and Minecraft Schematic files (MTS v3/v4, old fixed NBT and new Sponge NBT) into Goxel2.

There's a catch though (it always has to be, right...?), these formats do store voxel images, but no colors, just names. So they only work if you select the proper palette on the UI, otherwise they will load the schematics as black & white images (more precisely black & transparent). Here are some palette samples, one for Minecraft and two for Minetest (in GIMP Palette format, I don't think it's a good idea to embed these in Goxel2, because the point is users can change the colors and / or add new blocks easily when they need them for a schematic.)

[palettes.tgz](https://github.com/goxel2/goxel2/files/9276268/palettes.tgz)

Oh, **VERY IMPORTANT**, in `src/palette.h` please *increase the palette entry name's size*. The current 32 byte simply not enough for Minecraft names (like "minecraft:light_gray_glazed_terracotta"), furthermore these importers allow alias names separated by a slash (like "minecraft:wooden_slab/minecraft:oak_slab" for example).
```diff
typedef struct {
    uint8_t  color[4];
-    char     name[32];
+    char     name[256];
} palette_entry_t;
```
No other modifications necessary, however I haven't looked into it, but when the user selects a palette and hovers the mouse over a color, it might be worth showing the name of that color in a popup tooltip (it looks like all built-in palette colors already have names, and also loaded from .gpl files, just not shown on the UI).

Cheers,
bzt

**Comment by pegvin** [comment]
seems like god itself wants this project to grow, xd, thanks for your efforts! i will look into it!

Cheers!

**Comment by pegvin** [comment]
So i looked at it, currently i can't convert the gpl files into inl because of some error in python script but i was able to make it work by putting it into the palette dir (`~.config/goxel2/palettes`) and it loaded up normally, the thing i noticed was the colors were applied according to currently selected palette, so we can do one thing, that is we can let the user select which palette to use in the 3 palettes you've given.

**Comment by pegvin** [comment]
also the canvas size doesn't seem to adapt to the size of the model, which i'm tryin to fix.

**Comment by pegvin** [comment]
Well seems like you're on windows, and on windows the new line is `\r\n` and not `\n` and that was why the python script was creating some issues, i've patched the script so it converts the platform independent new line feeds to simple `\n`

**Comment by bztsrc** [comment]
> i can't convert the gpl files into inl because of some error in python script

Don't do that.

> it work by putting it into the palette dir (~.config/goxel2/palettes)

That's the expected behavior. As I've said, users should be able to modify and add new block colors without recompiling.

> i noticed was the colors were applied according to currently selected palette

Yep. This way the user can select the palette easily, and no complex UI required.

> we can let the user select which palette to use in the 3 palettes you've given.

There's no 1-by-1 relation between the formats and the palettes, what's more, the user should be able to change the palette to match what's in *their* schems (both Minecraft new NBT and MTS is moddable, meaning new block names can appear any time).

> Well seems like you're on windows, and on windows the new line is \r\n and not \n 

Nope, I've generated those. My programs always generate `\r\n` because I usually write multiplatform apps.

> i've patched the script so it converts the platform independent new line feeds to simple \n

Again, **DO NOT** embed the palettes, they are subject to rapid change!

Cheers,
bzt

**Comment by bztsrc** [comment]
Hi, added a proposed solution to the "embedded palettes aren't modifiable" problem, see issue #19.

Cheers,
bzt

**Comment by pegvin** [comment]
so palettes and stuff is different topic, close this issue, i'll raise a new issue and we can talk there, i'd be glad if there is some other place we could talk together.

Cheers.
aditya

**Comment by bztsrc** [comment]
> so palettes and stuff is different topic, close this issue, i'll raise a new issue and we can talk there

Not entirely different, because schematic formats need named colors, but okay, I'll close it. I also believe this part is done, plus the necessary named colors are embedded already.

Cheers,
bzt
