### ISSUE TITLE
Allow Users To Edit Built-In Palettes

### ISSUE THREAD

**Issue by bztsrc** [goxel2/goxel2#19]
Hi,

Here's a fix for the "built-in palettes are not modifiable" problem mentioned in issue #17.

[palette.c.gz](https://github.com/goxel2/goxel2/files/9277194/palette.c.gz)

This is how it works:

1. if there's no HOME, then just uses the built-ins as before
2. if HOME exists, but `~/.config/goxel2/palettes` dir not: it creates the directory and saves all built-in palettes there
3. if `~/.config/goxel2/palettes` exists and has palette files in it: then just uses the palettes read from the directory.

This solution has the advantage of combining the benefits from both worlds:
1. no need to separately distribute palette files (they are embedded)
2. yet users can modify the "Minetest.gpl" and "Minecraft.gpl" if they want to

Cheers,
bzt

**Comment by pegvin** [comment]
will take a look into the code, just a little busy with something.

**Comment by pegvin** [comment]
Hey, so i looked into the code and your idea is pretty great but before making a pr for this what do you think about separating the resources into different folders and ship them with the app?

Like if you see directory structure of magicavoxel's build there are different directories for UI, palettes, example models.

**Comment by pegvin** [comment]
hmm, makes sense.

**Comment by pegvin** [comment]
ah i've made the PR, i fixed stuff from getting overwritten because just as you i also thought that `sys_list_dir` returns numbers of entries it found, but actual function implementation did not and that's why it was returning 0 every time.

**Comment by bztsrc** [comment]
> it was returning 0 every time.

Oh, I have only tested the case when the directory didn't existed, sorry.

> sorry for merging it so late

Are you kidding me? :-) I've waited MONTHS for guillaumechereau without any response... You are very easy to work with!

> pain in my back.

I know that feeling, get a new chair ASAP.

> i've made the PR

Cool, I'll close this issue now! Thanks!

Cheers,
bzt
