### ISSUE TITLE
Selection tool enhancement - rectangular selection

### ISSUE THREAD

**Issue by YarlBoro** [goxel2/goxel2#22]
Hello!
Current selection tool is great in certain scenarios, but in general it is not optimal for quick or irregular selections.
I humbly suggest making a second mode for selection tool - rectangular selection, just like in image editors (Photoshop, etc.). Selection is flat rectangle, all voxels inside it are selected.
 
It makes carving out models very fast & efficient, especially in block-out phase. Adding selection to existing one or substracting selection with new selection would be infinitely useful too (i.e. mouse drag+ctrl adds selection to existing one).

This feature already exists in two other voxel editors (i.e. Qubicle), so it isn't unproven concept. I strongly believe it would be a very valuable addition to Goxel. That type of selections open up multiple possible workflows in regard to sculpting, shading, hierarchy modification, etc

Thanks in advance for consideration

**Comment by pegvin** [comment]
Thanks for raising the issue, will take a look into this.
