### ISSUE TITLE
License must be GPLv3 I'm afraid

### ISSUE THREAD

**Issue by bztsrc** [goxel2/goxel2#33]
Hi,

You say in the readme that new files will be licensed under unlicense. I'm afraid GPLv3 does not allow that. I'm sorry, I know you wanted to go away from GPLv3 to a more permissive license, but legally you must license Goxel2 under GPLv3 until all originally GPLv3 licensed parts gets rewritten or replaced.

Here's the legal mambo-jumbo from [GPLv3 section 5c](https://www.gnu.org/licenses/gpl-3.0.en.html):
```
c) You must license the entire work, as a whole, under this License to anyone who comes
into possession of a copy. This License will therefore apply, along with any applicable
section 7 additional terms, to the whole of the work, and all its parts, regardless of how
they are packaged. This License gives no permission to license the work in any other
way, but it does not invalidate such permission if you have separately received it.
```
The key sentence here is `This License apply to the whole of the work, and all its parts`. See also [FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic)
```
Linking a GPL covered work statically or dynamically with other modules is making
a combined work based on the GPL covered work. Thus, the terms and conditions
of the GNU General Public License cover the whole combination.
```
So if you have multiple source files with different licenses, and one of them is GPLv3, then the only way to (legally) compile them together is if all source files are relicensed under GPLv3. For the records, this is fine by MIT and BSD 2/3-clause licenses, as those are compatible and allow relicensing under GPLv3 (see [here](https://www.gnu.org/licenses/license-list.html), that list refers to BSD/2 as the "FreeBSD" license, BSD/3 as "ModifiedBSD" and MIT as "expat", and Open Font as "SILOFL").

Hope this helps!
bzt

**Comment by pegvin** [comment]
ah f...

**Comment by bztsrc** [comment]
> ah f...

Yeah, but it's not that bad. Having a copyleft license such as GPL has its silver lining. It forces all derivative projects to be open source too. For example a company cannot just take a GPL'd project, rebrand it and sell it as if it were their product. Actually Cisco did that with Linux, and they have failed on court miserably.
Should Linux choose a much permissive license like MIT or Unlicense, and Cisco could get away with stealing the software and making huge profit on someone else's work.

Anyway, this isn't really an issue, I just wanted to let you know, that even though some parts aren't GPL'd, and new files are created under Unlicense, legally Goxel2 as a whole still remains GPL'd. And this isn't necessarily a bad thing.

Cheers,
bzt
